### ISSUE TITLE
ESLint Flat Config

### ISSUE THREAD

**Issue by trusktr** [prettier/eslint-config-prettier#253] opened 2023-06-26 03:38 UTC
Does this work with ESLint's new Flat Config format yet? If not (I didn't have any luck), I'd like to make this a feature request (or a doc update request as the README didn't mention flat configs)

**Comment by lydell** [comment] 2023-06-26 04:52
Duplicate of https://github.com/prettier/eslint-config-prettier/issues/231

**Closed by lydell** 2023-06-26 04:52 UTC
